/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0c0e10',
        'surface-container-low': '#1a1c1e',
        'surface-container': '#1e2022',
        'surface-container-high': '#282a2c',
        'surface-container-highest': '#333537',
        'surface-bright': '#37393b',
        'surface-variant': '#333537',
        'surface-dim': '#121416',
        surface: '#121416',
        background: '#121416',
        'on-surface': '#e2e2e5',
        'on-surface-variant': '#cbc6bb',
        'on-background': '#e2e2e5',
        'inverse-surface': '#e2e2e5',
        'inverse-on-surface': '#2f3133',
        outline: '#949087',
        'outline-variant': '#49473f',
        'surface-tint': '#ccc6b5',
        primary: '#f1ead8',
        'on-primary': '#333025',
        'primary-container': '#d4cebd',
        'on-primary-container': '#5b584a',
        'inverse-primary': '#625e51',
        'primary-fixed': '#e9e2d1',
        'primary-fixed-dim': '#ccc6b5',
        'on-primary-fixed': '#1e1c11',
        'on-primary-fixed-variant': '#4a473a',
        secondary: '#c2c9b9',
        'on-secondary': '#2c3227',
        'secondary-container': '#42493d',
        'on-secondary-container': '#b0b7a8',
        'secondary-fixed': '#dee5d4',
        'secondary-fixed-dim': '#c2c9b9',
        'on-secondary-fixed': '#171d13',
        'on-secondary-fixed-variant': '#42493d',
        tertiary: '#ffe5dc',
        'on-tertiary': '#442a20',
        'tertiary-container': '#efc5b7',
        'on-tertiary-container': '#6f5045',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#e7bdaf',
        'on-tertiary-fixed': '#2c160d',
        'on-tertiary-fixed-variant': '#5d4035',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xxl: '64px',
        base: '4px',
        xl: '40px',
        lg: '24px',
        md: '16px',
        'margin-desktop': '48px',
        sm: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        xs: '4px',
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
